### ISSUE TITLE
Linker command failed with boost::mpi

### ISSUE THREAD

**Issue by shinaoka** [ALPSCore/ALPSCore-Python#8]
Hello,

I am trying to build this module on my laptop (Mac OS X 10.11.16) with mpicxx-openmpi-clang38 (macports) and boost 1.59.0 (with the boost mpi library).
 
I got the following error message, indicating that the boost mpi library is not linked.
After exploring the ALPSCore libraries, I found that the target libraries are actually set here:
https://github.com/ALPSCore/ALPSCore-Python/blob/master/common/cmake/ALPSCommonModuleDefinitions.cmake#L178

It seems that we need to add boost::mpi as well.
Is my understanding  correct?

Best,
Hiroshi

======================================================================
[ 26%] Linking CXX shared module pymcbase_c.so
cd /Users/hiroshi/build/alpscore-python/mc && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/pymcbase_c.dir/link.txt --verbose=1
/opt/local/bin/mpicxx-openmpi-clang38  -std=c++14 -O3 -DNDEBUG -bundle -Wl,-headerpad_max_install_names  -o pymcbase_c.so CMakeFiles/pymcbase_c.dir/src/pymcbase.cpp.o /usr/lib/libpython2.7.dylib /opt/ALPSCore/lib/libalps-mc.dylib /opt/ALPSCore/lib/libalps-gf.dylib /opt/boost_1_59_0/lib/libboost_python.dylib /opt/ALPSCore/lib/libalps-accumulators.dylib /opt/ALPSCore/lib/libalps-params.dylib /opt/boost_1_59_0/lib/libboost_serialization.dylib /opt/ALPSCore/lib/libalps-hdf5.dylib /opt/ALPSCore/lib/libalps-utilities.dylib /opt/boost_1_59_0/lib/libboost_chrono.dylib /opt/boost_1_59_0/lib/libboost_filesystem.dylib /opt/boost_1_59_0/lib/libboost_system.dylib /opt/boost_1_59_0/lib/libboost_program_options.dylib /opt/local/lib/libhdf5_cpp.dylib /opt/local/lib/libhdf5.dylib /usr/lib/libz.dylib /usr/lib/libdl.dylib /usr/lib/libm.dylib -Wl,-rpath,/opt/boost_1_59_0/lib 
Undefined symbols for architecture x86_64:
  "boost::mpi::communicator::communicator()", referenced from:
      boost::python::objects::value_holder<alps::pymcbase>::value_holder<boost::python::objects::reference_to_value<boost::python::dict>, unsigned long>(_object*, boost::python::objects::reference_to_value<boost::python::dict>, unsigned long) in pymcbase.cpp.o
      boost::python::objects::value_holder<alps::pymcbase>::value_holder<boost::python::objects::reference_to_value<boost::python::dict> >(_object*, boost::python::objects::reference_to_value<boost::python::dict>) in pymcbase.cpp.o

**Comment by galexv** [comment]
ALPSCore itself used to provide transitive dependence on `boost::mpi`. Now `boost:mpi` is not used, so i have modified the code (commit 1d50ec334b) to use `alps::mpi` instead &mdash; hope this works.
